name: task_manager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # Les dépendances que vous avez demandées
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.6.0
  provider: ^6.0.0
  http: 1.2.2
  image_picker: ^0.8.6
  # La dépendance pour les icônes Cupertino (iOS)
  cupertino_icons: ^1.0.8
  firebase_storage: 12.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Package de lints pour encourager de bonnes pratiques de codage
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Si vous avez des assets à ajouter
  assets:
    - assets/auth_illustration.png
    - assets/register_logo.png

  # Si vous souhaitez ajouter des polices personnalisées
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
